version: 0.2

phases:
  install:
    runtime-version: 
      nodejs: 14

  pre-build:
    # We are restoring node_modules folder back
    commands:
      - npm install
    
  build:
    # Generating our build folder
    commands:
      - node --version
      - npm run build

artifacts: 
  files:
    - 'Dockerfile'
    - 'build/**/*'